[project]
name = "fast-coref"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hydra-core>=1.3.2",
    "omegaconf>=2.3.0",
    "scipy>=1.14.1",
    "torch>=2.5.1",
    "transformers>=4.47.1",
    "wandb>=0.19.1",
]
